### PR TITLE
more npe protection if build missing annotations

### PR DESCRIPTION
**Pull request by gabemontero**
analogous change to recent cd team discovered bug https://github.com/openshift/jenkins-sync-plugin/issues/180

### CODE REVIEW

**Comment by gabemontero** [comment]
[test]

**Comment by bparees** [comment]
lgtm

**Comment by gabemontero** [comment]
[merge]

**Comment by gabemontero** [comment]
A fair amount of networking to the master pain in the test run .... let's see if it continues during the merge job

**Comment by gabemontero** [comment]
yep the merge test run was clean ... cool

**Pull request merged**
