### PR TITLE
bump okhttp max concurrent watch conns past 5 total

### PR DESCRIPTION
**Pull request by gabemontero**
Fixes https://github.com/openshift/jenkins-sync-plugin/issues/227

(and several other bugzillas/issues in this space recently which have been mitigated through other means)

@openshift/sig-developer-experience ptal

### CODE REVIEW

**Comment by bparees** [comment]
@gabemontero sorry I didn't follow what changed/broke us?  Shouldn't any change have provided api compatibility?

**Comment by gabemontero** [comment]
@bparees actually I'm still sorting out the specifics as I work on the fix, but the "kind" we are getting back is not what it used to be, and it messes with the narrow/related logic.

I'll provide a detailed explanation in the PR I submit against jenkins-client-plugin ... I'll cross ref that one here, but it also showed up in last night build-ext-test run.

**Comment by bparees** [comment]
> I'll provide a detailed explanation in the PR I submit against jenkins-client-plugin ... I'll cross ref that one here, but it also showed up in last night build-ext-test run.

the implication would be that something just changed in v3.10 that will break jenkins v3.9 images running on a v3.10 cluster.  That shouldn't happen.

**Comment by gabemontero** [comment]
On Thu, Apr 19, 2018 at 4:06 PM, Ben Parees <notifications@github.com>
wrote:

> I'll provide a detailed explanation in the PR I submit against
> jenkins-client-plugin ... I'll cross ref that one here, but it also showed
> up in last night build-ext-test run.
>
> the implication would be that something just changed in v3.10 that will
> break jenkins v3.9 images running on a v3.10 cluster. That shouldn't happen.
>
I suspect it works ok from an `oc` perspective ... there is some analysis
of the `oc get` output that the groovy dsl layer does ... that
appears to have been broken by a recent 3.10 change.

**Pull request merged**
