### PR TITLE
map sync plugin tests in openshift/origin into this repo

### PR DESCRIPTION
**Pull request by gabemontero**
@openshift/openshift-team-build-api @openshift/team-devtools-jenkins  per recent updates in scrum, here is the e2e port from openshift/origin into this repo

Once we merge this, next steps are 

1) update openshift/release with new repo only operator CI jobs like we have for the client plugin
2) vendor these tests and the client plugin tests into openshift/jenkins, and then call them from a new in repo operator style test suite for that repo
3) we can reduce the jenkins suite in openshift/origin to minimal sniff test where only a single, simplistic pipeline strategy build like this  is called

```
node() {
  exit 0
}
```
4) and if we want, even disable e2e-aws-jenkins in our jenkins related repos, as we know have the same coverage elsewhere

### CODE REVIEW

**Review by adambkaplan — CHANGES_REQUESTED** [review]
I don't think `go fmt` was applied here. Do we have a `verify` test that checks this?

**Comment by gabemontero** [comment]
> I don't think `go fmt` was applied here. Do we have a `verify` test that checks this?

I ran it a few times but perhaps not most recently.

Sure I'll add a verify.

**Comment by gabemontero** [comment]
According to gofmt my branch was already OK @adambkaplan :+1: 
```
gmontero ~/go/src/github.com/openshift/jenkins-sync-plugin  (in-repo-e2e)$ gofmt -w ./test
gmontero ~/go/src/github.com/openshift/jenkins-sync-plugin  (in-repo-e2e)$ git status 
On branch in-repo-e2e
nothing to commit, working tree clean
gmontero ~/go/src/github.com/openshift/jenkins-sync-plugin  (in-repo-e2e)$ git push origin in-repo-e2e
Everything up-to-date
gmontero ~/go/src/github.com/openshift/jenkins-sync-plugin  (in-repo-e2e)$ 
```

that said I'll still add a verify

**Comment by gabemontero** [comment]
`make verify` for gofmt added @adambkaplan

**Comment by gabemontero** [comment]
/assign @coreydaley 
/assign @akram 

the moving of jenkins sync plugins e2e's from openshift/origin to this repo

after we iterate on this and merge, I'll start on the changes, similar to what Adam did for the shared resource stuff, so that we can use these tests and the client plugin tests in the openshift/jenkins repo, and move of having to use e2e's defined in openshift/origin

**Comment by coreydaley** [comment]
@gabemontero Were you able to verify in the logs that the tests that you moved were indeed run?

**Comment by gabemontero** [comment]
> @gabemontero Were you able to verify in the logs that the tests that you moved were indeed run?

Yes @coreydaley I manually ran this entire suite against my personal cluster, if that is what you mean.

Forgot to mention previously, before doing the changes so these tests can be invoked from openshift/jenkins, once this PR merges, I'll craft a simpler openshift/release PR for the existing configuration for this repo to invoke these tests.  But I will leave e2e-aws-jenkins short term.

I'll craft a test PR against this repo to make sure both tests are run.  Once all is good, I'll update the openshift/release config for this repo to no longer call e2e-aws-jenkins from openshift/origin.

Then I'll move on to openshift/jenkins .... similarly, at the moment, we have both test suites in the client plugin.  Check out the latest PR there:  https://github.com/openshift/jenkins-client-plugin/pull/365

I'll similarly be updating the openshift/release client plugin config to punt on e2e-aws-jenkins once we are ready.

**Pull request merged**
