### PR TITLE
bump pipeline-rest-client to avoid intermittent linkage error with ja…

### PR DESCRIPTION
**Pull request by gabemontero**
…cksonxml

Addresses intermittent (yes, surprisingly intermittent) errors of this ilk:

```
java.lang.LinkageError: loader constraint violation: when resolving method "com.fasterxml.jackson.databind.ObjectMapper.<init>(Lcom/fasterxml/jackson/core/JsonFactory;)V" the class loader (instance of hudson/PluginFirstClassLoader) of the current class, io/fabric8/kubernetes/client/utils/Serialization, and the class loader (instance of hudson/PluginFirstClassLoader) for the method's defining class, com/fasterxml/jackson/databind/ObjectMapper, have different Class objects for the type com/fasterxml/jackson/core/JsonFactory used in the signature
	at io.fabric8.kubernetes.client.utils.Serialization.<clinit>(Serialization.java:38)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.<clinit>(OperationSupport.java:59)
	at io.fabric8.openshift.client.DefaultOpenShiftClient.imageStreams(DefaultOpenShiftClient.java:332)
	at io.fabric8.jenkins.openshiftsync.ImageStreamWatcher$1.doRun(ImageStreamWatcher.java:65)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:51)
	at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

@openshift/devex fyi

### CODE REVIEW

**Comment by gabemontero** [comment]
[test]

**Comment by bparees** [comment]
huh. nice find.
lgtm

**Comment by gabemontero** [comment]
the test is still cooking, but I'm seeing some odd environmental-ish errors contacting the jenkins pod;
I'll let the run finish, and then give @bparees 's new generic pod dump diagnostics a whirl

**Comment by gabemontero** [comment]
Hmm ... no evidence of the string `Dumping pod state for namespace` in the console output.

@bparees - do we have to do something explicit in the tests to ensure  `g.CurrentGinkgoTestDescription().Failed` is true on a failure?

I do see evidence of two jenkins pods in the logging of pods the kubelet thinks exists as part of the e2e diagnostics:

```
Oct  4 16:33:15.429: INFO: jenkins-1-sg3qr                            ip-172-18-15-249.ec2.internal  Running           [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-10-04 16:14:36 +0000 UTC  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2017-10-04 16:15:26 +0000 UTC  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-10-04 16:14:36 +0000 UTC  }]
Oct  4 16:33:15.429: INFO: jenkins-sync-plugin-snapshot-test-1-build  ip-172-18-15-249.ec2.internal  Succeeded         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-10-04 16:09:40 +0000 UTC PodCompleted } {Ready False 0001-01-01 00:00:00 +0000 UTC 2017-10-04 16:14:27 +0000 UTC PodCompleted } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-10-04 16:09:27 +0000 UTC  }]
Oct  4 16:33:15.429: INFO: jenkins-1-hkx6p                            ip-172-18-15-249.ec2.internal  Running           [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-10-04 16:11:16 +0000 UTC  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2017-10-04 16:12:06 +0000 UTC  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-10-04 16:11:16 +0000 UTC  }]
Oct  4 16:33:15.429: INFO: jenkins-sync-plugin-snapshot-test-1-build  ip-172-18-15-249.ec2.internal  Succeeded         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-10-04 16:09:36 +0000 UTC PodCompleted } {Ready False 0001-01-01 00:00:00 +0000 UTC 2017-10-04 16:11:04 +0000 UTC PodCompleted } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-10-04 16:09:27 +0000 UTC  }]



Oct  4 16:33:15.459: INFO: jenkins-1-hkx6p started at 2017-10-04 16:11:16 +0000 UTC (0+1 container statuses recorded)
Oct  4 16:33:15.459: INFO: 	Container jenkins ready: true, restart count 0
Oct  4 16:33:15.459: INFO: jenkins-1-cxr8m started at 2017-10-04 16:16:46 +0000 UTC (0+1 container statuses recorded)
Oct  4 16:33:15.459: INFO: 	Container jenkins ready: true, restart count 0
```

That does not make sense to me at first blush.

The corresponding events only list `jenkins-1-hkx6p`, which is noted up top as part of the new-app call.

Is it possible there are other tests running on this node (as part of the parallel test execution)?

Otherwise, we are getting a 404 / Not Found on the http request to confirm the version of the sync plugin across the various tests.

Really need the jenkins pod logs to investigate ... though dumping the raw content of the http call would be helpful too.

Going to try locally as a sanity check, then, unless @bparees has some insight on the lack of pod logs, perhaps craft a PR to dump the http response text on this particular failure.

**Comment by bparees** [comment]
> @bparees - do we have to do something explicit in the tests to ensure g.CurrentGinkgoTestDescription().Failed is true on a failure?

no.  but doesn't this PR tester run using AMI?  the AMI probably hasn't picked up the extended test changes yet since they just merged.

**Comment by gabemontero** [comment]
ah, yeah that is probably it .... this isn't prow, etc.

Here is the step of note in the job:

```
#!/bin/bash
SCRIPT_START_TIME="$( date +%s )" && export SCRIPT_START_TIME && echo "########## STARTING STAGE: PROVISION CLOUD RESOURCES ##########" && trap 'export status=FAILURE' ERR && trap 'set +o xtrace; SCRIPT_END_TIME="$( date +%s )"; ELAPSED_TIME="$(( SCRIPT_END_TIME - SCRIPT_START_TIME ))"; echo "########## FINISHED STAGE: ${status:-SUCCESS}: PROVISION CLOUD RESOURCES [$( printf "%02dh %02dm %02ds" "$(( ELAPSED_TIME/3600 ))" "$(( (ELAPSED_TIME%3600)/60 ))" "$(( ELAPSED_TIME%60 ))" )] ##########"' EXIT && set -o errexit -o nounset -o pipefail -o xtrace && if [[ -s "${WORKSPACE}/activate" ]]; then source "${WORKSPACE}/activate"; fi
oct provision remote all-in-one --os "rhel" --stage "build" --provider "aws" --discrete-ssh-config --name "${JOB_NAME}_${BUILD_NUMBER}" 
```

ami_build_origin_int_rhel_base last built 19 hours ago, ami_build_origin_int_rhel_base 14 hours ago

**Comment by gabemontero** [comment]
OK I'm seeing this locally so will debug there.

I did figure out why we are not seeing the pod dump.  The jenkins setup occurs in a `g.BeforeEach` that is outside of the `g.Context` calls.  The pod dumps are placed in `g.AfterEach` instances within each `g.Context` (where we have a Context per test).

I'll look into how to best restructure (there are pros/cons to each option) as part of investigating.

**Comment by gabemontero** [comment]
Its the way we build our test image.  We don't override the existing `pipeline-rest-api` in the base jenkins image, and since we've bumped that to 2.9, it complains.

When you install the new sync plugin by the jenkins console install mgr, it resolves dependencies similar to our jenkins image dependency download and brings it in under the covers for us.

I'm going to see if I can trigger the "Downloading plugins.." logic in install-plugins.sh.  At the moment, that step is doing nothing when run form out PR tester script.

**Comment by gabemontero** [comment]
[test]

**Comment by gabemontero** [comment]
working for me locally now

**Comment by gabemontero** [comment]
there we go .... [merge]

**Pull request merged**
