### PR TITLE
protect against invalid secret data when mapping to credentials

### PR DESCRIPTION
**Pull request by gabemontero**
Fixes https://github.com/openshift/jenkins-sync-plugin/issues/207

@openshift/sig-developer-experience fyi

### CODE REVIEW

**Comment by gabemontero** [comment]
[test]

**Comment by gabemontero** [comment]
same install origin failure we've been seeing in the origin prs

I'll retest in a bit

**Comment by gabemontero** [comment]
[test]

**Comment by bparees** [comment]
lgtm

**Comment by gabemontero** [comment]
Yeah I've seen this a couple of times now ... the 5 minutes allocated to the build stage in our relatively new nodejs-sample-pipeline.yaml appears to be pushing it.  I've seen it intermittently time out, and then when I look the status for the `nodejs-mongodb-example-1` it is still running.

Going to submit a PR in origin to bump that up.

In parallel, going to retest here and see how intermittent the "slow" build is.

**Comment by gabemontero** [comment]
[test]

**Comment by gabemontero** [comment]
ok cool test passed ... I'll try the merge tag first, see if passes again, before hitting the button

**Comment by gabemontero** [comment]
[merge]

**Pull request merged**
