### PR TITLE
Support openshift client token credentials

### PR DESCRIPTION
**Pull request by joejstuart**
This adds support for syncing credentials to use with the Openshift client plugin.

### CODE REVIEW

**Comment by gabemontero** [comment]
ah ... a neat / quick / safe "optimization" for the client plugin's cred

thanks @joejstuart 

At some point a cross reference in the client plugin readme should be made to this ... if you can't get to it @joejstuart let me know and I'll get a to-do on my list to do it  ... just let me know if you can

/approve

/lgtm

@bparees - note the 3.11 based PR test jobs for the plugins are still working (vs. the 4.0 upheaval) ... I think this is what I expected ... don't know if you did

**Comment by joejstuart** [comment]
Thanks for the quick approval @gabemontero. I'm able to add the cross reference.

**Pull request merged**
