### PR TITLE
switch IS based auto pod template cfg to always pull image

### PR DESCRIPTION
**Pull request by gabemontero**
Fixes https://github.com/openshift/jenkins-sync-plugin/issues/186

@openshift/sig-developer-experience fyi

note, this method is only called in the image watch case

### CODE REVIEW

**Comment by gabemontero** [comment]
[test]

**Comment by bparees** [comment]
this covers labels imagestreams and annotated imagestreamtags right?  (your statement about it only handling images left me unclear)

**Comment by gabemontero** [comment]
On Tue, Dec 5, 2017 at 4:44 PM Ben Parees <notifications@github.com> wrote:

> this covers labels imagestreams and annotated imagestreamtags right? (your
> statement about it only handling images left me unclear)
>
sorry yeah, all of those

The key point of my unclear statement was supposed to be that this change
does not affect config maps

**Comment by bparees** [comment]
lgtm

**Comment by gabemontero** [comment]
[merge]

**Pull request merged**
