### PR TITLE
NPE on Bluerun.getNodes().iterator()

### LINKED ISSUE #286: NPE on bluerun.getNodes().iterator() during upsert build - in jenkins master version=v3.11.82
see https://github.com/opendevstack/ods-core/issues/86

on openshift 3.11 - latest 3.11 jenkins master & slaves

  | at io.fabric8.jenkins.openshiftsync.BuildSyncRunListener.upsertBuild(BuildSyncRunListener.java:336)
  | at io.fabric8.jenkins.openshiftsync.BuildSyncRunListener.pollRun(BuildSyncRunListener.java:226)
  | at io.fabric8.jenkins.openshiftsync.BuildSyncRunListener.onFinalized(BuildSyncRunListener.java:193)
  | at hudson.model.listeners.RunListener.fireFinalized(RunListener.java:257)
  | at hudson.model.Run.onEndBuilding(Run.java:1998)
  | at org.jenkinsci.plugins.workflow.job.WorkflowRun.finish(WorkflowRun.java:611)
  | at org.jenkinsci.plugins.workflow.job.WorkflowRun.access$900(WorkflowRun.java:132)
  | at org.jenkinsci.plugins.workflow.job.WorkflowRun$GraphL.onNewHead(WorkflowRun.java:993)
  | at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.notifyListeners(CpsFlowExecution.java:1440)
  | at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$3.run(CpsThreadGroup.java:417)
  | at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$1.run(CpsVmExecutorService.java:35)
  | at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
  | at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
  | at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
  | at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  | at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at java.lang.Thread.run(Thread.java:748) 

`Iterator<BluePipelineNode> iter = blueRun.getNodes().iterator();` is the NPE root ...

### PR DESCRIPTION
**Pull request by clemensutschig**
Fixes #286 
introduce null check for getNodes()

### CODE REVIEW

**Comment by clemensutschig** [comment]
fix also verified locally

image

**Comment by gabemontero** [comment]
thanks @clemensutschig !

**Comment by clemensutschig** [comment]
@gabemontero - Amy idea or process in what version of ocp this will show up? Current Master seems to be in 3.11x

**Comment by gabemontero** [comment]
On Wed, Mar 6, 2019 at 11:26 PM Clemens Utschig <notifications@github.com>
wrote:

> @gabemontero <https://github.com/gabemontero> - Amy idea or process in
> what version of ocp this will show up? Current Master seems to be in 3.11x
>

This will get into OCP 4.0 when it ships (currently targeted for April).

I have not cut a new version of the plugin yet cause there have been some
upstream changes that have seem to
rendered the current pom.xml out of date (my mvn release:prepare
release:perform yesterday failed).  I'll hopefully
get cycles either today or Monday to sort that out.  If I don't have to
pull Cloudbee support, it should be fairly straightforward.

As I am still able to cut new versions for the openshift client and login
plugins, I'm fairly optimistic I just need to get the pom.xml
in line with those.

But we'll see.....

**Comment by clemensutschig** [comment]
@gabemontero - thanks ... we have a  local version which I assume will work on the 3.11(x) line ... correct?

**Comment by gabemontero** [comment]
On Thu, Mar 7, 2019 at 10:19 AM Clemens Utschig <notifications@github.com>
wrote:

> @gabemontero <https://github.com/gabemontero> - thanks ... we have a
> local version which I assume will work on the 3.11(x) line ... correct?
>
Correct

**Pull request merged**
