### PR TITLE
Updating to latest OpenShift Client

### PR DESCRIPTION
**Pull request by coreydaley**

### CODE REVIEW

**Comment by coreydaley** [comment]
@gabemontero ptal

**Comment by gabemontero** [comment]
Let's see how the results go ... changing the client this deep into 3.10 is a conversation point.  There are pros/cons from stability to facilitating migrating fabric/openshift.io features to this repo.  I'm leaning toward merging if test looks good, but a due diligence discussion is needed.

@bparees

**Comment by bparees** [comment]
yeah i'm averse to doing this for 3.10 unless it is fixing any known issues, i already relabeled the card to proposed 3.11.

**Comment by bparees** [comment]
(but certainly getting a headstart on the sniff testing makes sense)

**Comment by coreydaley** [comment]
I'm fine with it waiting until 3.11, just saw the announcement and thought I could start the testing now.

**Comment by coreydaley** [comment]
@gabemontero Looks like the test is passing, is there anything else specific you would like me to test/check?

**Comment by gabemontero** [comment]
not right now @coreydaley - let's just sit tight until we cut the 3.10 jenkins image, and then we'll merge this in the first 3.11 jenkins image builds to get maximum exposure / soak time.

@piyush1594 fyi - we have validated the 3.1.11 version of the fabric k8s client against our regression bucket.  The imagestreamtag retrievals are working successfuly.

This should also remove a key barrier in migrating fabric job-to-bc features currently not in upstream openshift sync plugin into upstream.

**Comment by piyush1594** [comment]
Thanks a lot for testing and confirming it. Let me know or else you know the process just create an issue there if you face any other problem. I will be happy to fix the issues on kubernetes-client and kubernetes-model.

**Comment by coreydaley** [comment]
[(3) Update fabric k8s client in jenkins sync plugin [jenkins_integration]](https://trello.com/c/9882Gnrt/1488-3-update-fabric-k8s-client-in-jenkins-sync-plugin-jenkinsintegration)

**Comment by gabemontero** [comment]
install origin pain ... noticed a recent flurry of commits in aos-cd-jobs ... perhaps a regression has been introduced there

will try retesting one more time here, but based on prior successful tests, will hit merge button is needed

**Pull request merged**
