### PR TITLE
revert fabric8 bump, work around 3.6 api svr issue

### PR DESCRIPTION
**Pull request by gabemontero**
(short term) Fixes https://github.com/openshift/jenkins-sync-plugin/issues/173

@openshift/devex fyi

### CODE REVIEW

**Comment by gabemontero** [comment]
[test]

**Comment by bparees** [comment]
@gabemontero this version of the fabric plugin is compatible with both 3.6 and the current 3.7?  if so, i'm definitely in agreement.

**Comment by gabemontero** [comment]
the PR test that just ran confirms current 3.7

I bringing up `oc cluster up --version=v3.6.0` as I type .... will update with results when I have them.

**Comment by gabemontero** [comment]
Confirmed .... reproduced the problem with openshift/origin v3.6.0; then upgraded jenkins to my locally built version of this PR, and the error goes away.

**Comment by gabemontero** [comment]
[merge]

**Pull request merged**
