### PR TITLE
avoid potential NPE on switch if build run policy inexplicably null

### PR DESCRIPTION
**Pull request by gabemontero**
Fixes https://github.com/openshift/jenkins-sync-plugin/issues/172

### CODE REVIEW

**Comment by gabemontero** [comment]
[test]

**Comment by gabemontero** [comment]
will merge after 137 ... the NPE was in a fabric8 one off and not seen yet in our testing ... so viewing as low priority

**Comment by bparees** [comment]
lgtm

**Comment by gabemontero** [comment]
[merge]

**Pull request merged**
