### PR TITLE
support syncing multiple namespaces

### PR DESCRIPTION
**Pull request by bparees**
fixes bug https://bugzilla.redhat.com/show_bug.cgi?id=1390288

### CODE REVIEW

**Comment by bparees** [comment]
@jimmidyson would appreciate you giving this a review since it's the first major change to the plugin.

@gabemontero ptal also

**Comment by gabemontero** [comment]
LGTM

**Comment by bparees** [comment]
@gabemontero i'm going to merge this on the optimistic assumption that we won't be packaging a new rhel version of the plugin for 3.5 at this point.

**Comment by gabemontero** [comment]
10-4 @bparees - do you want to take a stab at cutting a new sync plugin release in jenkins upstream, or would you like me to?

**Comment by bparees** [comment]
@gabemontero i'll take a crack at it.

**Pull request merged**
