### PR TITLE
Fix duplicate job run parameters

### PR DESCRIPTION
**Pull request by vfreex**
Triggering a job run from Jenkins UI or triggers defined in the job
could cause duplicate parameters. This is caused by missing checks
between the build strategy parameters and user specified parameters.

Using LinkedHashMap instread of ArrayList for parameters can
solve this issue, where the user specified parameters are able to overrides those defined in the build strategy silently.

Reproduction:
Create a BuildConfig on OpenShift with JenkinsPipelineBuildStrategy, define an environment variable `NAME`. Note there is a cron trigger that triggers this job every 3 minutes.

```yaml
kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "demo-pipeline"
spec:
  strategy:
    jenkinsPipelineStrategy:
      env:
      - name: "NAME"
        value: "openshift"
      jenkinsfile: |-
        pipeline {
          agent {
            kubernetes {
              cloud 'openshift'
              label "jenkins-slave-${UUID.randomUUID().toString()}"
              yaml """
              apiVersion: v1
              kind: Pod
              metadata:
                labels:
                  app: "my-jenkins-slave"
              spec:
                containers:
                - name: jnlp
                  image: docker.io/openshift/jenkins-slave-base-centos7:latest
                  tty: true
                  resources:
                    requests:
                      memory: 512Mi
                      cpu: 200m
              """
            }
          }
          triggers { cron('*/3 * * * *') }
          stages {
            stage('foo') {
              steps {
                echo "Hello, ${params.NAME}"
              }
            }
          }
        }
```
Then start a job run with `oc start-build demo-pipeline` to let Jenkins Sync plugin create a Jenkins job.
Next, start a job run from Jenkins UI, or wait for a new job run started by the cron trigger. You should see there are 2 duplicate parameters with the same name.

### CODE REVIEW

**Comment by vfreex** [comment]
A bug is reported to Red Hat Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1622014

**Comment by gabemontero** [comment]
thanks @vfreex !

**Comment by gabemontero** [comment]
v 1.0.26 of the sync plugin has been initiated

**Pull request merged**
