### PR TITLE
fix ChoiceParameterDefinition typo

### PR DESCRIPTION
**Pull request by gabemontero**
from users mailing list

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
@bparees FYI there are not enough OWNERS in this repo to assign people to these PRs

**Comment by bparees** [comment]
@stevekuznetsov i'm ok w/ that, i hate the automated assignment :)

**Comment by gabemontero** [comment]
I’m also OK with no auto assign.  Both @bparees and I get notified on all
this repo’s activity.

**Comment by stevekuznetsov** [comment]
Might want to remove `blunderbuss` from your repo's config then

**Comment by gabemontero** [comment]
v1.0.21 of the plugin has been initiated with this fix

**Pull request merged**
