### PR TITLE
retry on exising job load collsion after jenkins restart

### PR DESCRIPTION
**Pull request by gabemontero**
Fixes https://github.com/openshift/jenkins-sync-plugin/issues/117

OK, to the intended repo this time :-)

@bparees @jimmidyson ptal

@jimmidyson - per the suggestion in my misguided PR to jenkinsci, I don't think the ItemListener really helps us here; it boils done to having to wait a sufficient amount of time to ensure all the onLoaded events have fired; I *don't* see where there is a truly deterministic way to determine that from a plugin perspective ... and I don't want to wait some arbitrary amount of time to get things going, and so decided on keeping the retry .. but of course we can discuss further as desired

### CODE REVIEW

**Comment by bparees** [comment]
lgtm but let's see what @jimmidyson says based on your latest comments.

**Comment by jimmidyson** [comment]
LGTM. Shame on Jenkins for being so non-deterministic on startup :(

**Comment by gabemontero** [comment]
thx gentlemen ... merging ...

**Comment by gabemontero** [comment]
OK my hitting of the merge button did not do what I expected ... I'm not seeing commit https://github.com/openshift/jenkins-sync-plugin/commit/d410ee588c3d60d6654db6112468953a49aa76cd in the master branch ... only in the 117 branch.

@bparees - is there perhaps some repo setup that is not quite right for openshift/jenkins-sync-plugin ?

**Comment by bparees** [comment]
you submitted this PR against the openshift:117 branch, not the openshift:master branch.

**Comment by gabemontero** [comment]
hmm... don't even know how that happened ... i believe i followed the same recipe of 
- fork the openshift/jenkins-sync-plugin repo to gabemontero/jenkins-sync-plugin repo
- created a branch locally, made change 
- did a `git push origin <branch name>` ... where `origin` points to gabemontero/jenkins-sync-plugin when i do a `git remote -v`

**Comment by gabemontero** [comment]
i'll try to respin the change i suppose ....

**Comment by gabemontero** [comment]
... and remove that branch

**Comment by bparees** [comment]
doesn't matter where you pushed to within your repo(origin), only matters what options you chose when you created the PR.

**Comment by bparees** [comment]
you should be able to just create another PR, this time against master.

**Comment by gabemontero** [comment]
must have accidently chose the wrong branch on the pr  create (certainly did not explicitly select the other branch) ... doing a new PR now

**Pull request merged**
