### PR TITLE
Fix spelling error in README

### PR DESCRIPTION
**Pull request by major**
Fixed a spelling error in this sentence:

```
change the configuration of the Kuberentes Cloud plugin running in Jenkins to add
```

### CODE REVIEW

**Comment by bparees** [comment]
@gabemontero this is failing to run under travis because it's timing out downloading maven deps.

not sure if that's a temporary issue or permanent (looks like it ran for 49 minutes).  have you had any other PRs against this repo pass travis lately?

**Comment by bparees** [comment]
i've restarted the travis build, in retrospect it was probably just a one time glitch, just that travis doesn't get rerun on failure.

**Comment by gabemontero** [comment]
On Mon, Sep 17, 2018 at 5:39 PM Ben Parees <notifications@github.com> wrote:

> @gabemontero <https://github.com/gabemontero> this is failing to run
> under travis because it's timing out downloading maven deps.
>
> not sure if that's a temporary issue or permanent (looks like it ran for
> 49 minutes). have you had any other PRs against this repo pass travis
> lately?
>
not lately

I think I remember this happening once or twice

**Pull request merged**
